import { atom } from 'recoil';
import { topcutDefaultValue } from '../types/scoreboardDefaultValue';

export const topcutAtom = atom({
  key: 'topcutAtom',
  default: {
    Player1: topcutDefaultValue,
    Player2: topcutDefaultValue,
    Player3: topcutDefaultValue,
    Player4: topcutDefaultValue,
    Player5: topcutDefaultValue,
    Player6: topcutDefaultValue,
    Player7: topcutDefaultValue,
    Player8: topcutDefaultValue,
    Player9: topcutDefaultValue,
    Player10: topcutDefaultValue,
    Player11: topcutDefaultValue,
    Player12: topcutDefaultValue,
    Player13: topcutDefaultValue,
    Player14: topcutDefaultValue,
    Player15: topcutDefaultValue,
    Player16: topcutDefaultValue,
    Player17: topcutDefaultValue,
    Player18: topcutDefaultValue,
    Player19: topcutDefaultValue,
    Player20: topcutDefaultValue,
    Player21: topcutDefaultValue,
    Player22: topcutDefaultValue,
    Player23: topcutDefaultValue,
    Player24: topcutDefaultValue,
    Player25: topcutDefaultValue,
    Player26: topcutDefaultValue,
    Player27: topcutDefaultValue,
    Player28: topcutDefaultValue,
    Player29: topcutDefaultValue,
    Player30: topcutDefaultValue,
    Player31: topcutDefaultValue,
    Player32: topcutDefaultValue,
  },
});
